POST   http://localhost:7071/api/ProcessHtmlDoc
Content-Type: application/json

{
    "id": "4",
    "docUrl": "https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-cni-overlay-in-azure-kubernetes-service/" 
}